spring.application.name=sa-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:lZDAuroxgcpZUUxLuEkehcNKMuGvvMDx}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

server.port=${PORT:8080}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:agriscantech@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:aousepdmxbdbtqsz}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

management.health.mail.enabled=false
management.endpoints.web.exposure.include=health

# ?? Upload ?????????????????????????????????????????????????
upload.dir=uploads/photos
server.base-url=https://agriscan-backend-04bd.onrender.com

# Taille max fichier upload (5 Mo)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB